import * as esbuild from "esbuild";
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

// ── Pass 0: bundle the browser client into the served HTML ───────────
//
// The browser client is bundled to an in-memory string and inlined into
// the static `index.html` template. The combined HTML is then written to
// a gitignored generated file that gravity-server.ts imports as
// `CLIENT_HTML_TEMPLATE`, mirroring the way the pi extension is bundled
// to `PI_EMITTER_SOURCE`. The `%%GRAVITY_TOKEN%%` placeholder is
// substituted once at server startup — the bundle itself stays
// token-agnostic, so the same artifact works for every gateway start.

const clientResult = await esbuild.build({
  entryPoints: ["src/gateway/client/index.ts"],
  bundle: true,
  platform: "browser",
  target: "es2020",
  format: "iife",
  write: false,
});

if (!clientResult.outputFiles || clientResult.outputFiles.length === 0) {
  throw new Error("esbuild client pass produced no outputFiles");
}
const clientJsText = clientResult.outputFiles[0].text;

const htmlTemplatePath = "src/gateway/client/index.html";
const htmlTemplate = readFileSync(htmlTemplatePath, "utf8");
const scriptTag = `<script>\n${clientJsText}\n</script>`;
// Function replacement — a plain string here would mangle `$$`/`$&`
// sequences in the bundled JS (String.replace treats them as patterns).
const inlinedHtml = htmlTemplate.replace(
  "<!-- GRAVITY_CLIENT_SCRIPT -->",
  () => scriptTag,
);

const clientBundleGeneratedPath = "src/gateway/client-bundle.generated.ts";
const clientBundleHeader = "// AUTO-GENERATED by build.mjs — do not edit by hand.\n";
const clientBundleFileBody =
  clientBundleHeader +
  `export const CLIENT_HTML_TEMPLATE: string = ${JSON.stringify(inlinedHtml)};\n`;
mkdirSync(dirname(clientBundleGeneratedPath), { recursive: true });
writeFileSync(clientBundleGeneratedPath, clientBundleFileBody, "utf8");

// ── Pass 1: bundle the pi extension into an in-memory string ────────
//
// The extension is embedded as a string constant in the server build so
// `dist/gravity-server.mjs` is fully self-contained at runtime (no
// sibling artifact lookup, no `__dirname` reads for the emitter). See
// plan.md §2 "Distribution mechanism" for why this shape was chosen.

const emitterResult = await esbuild.build({
  entryPoints: ["src/pi-driver/emitter/index.ts"],
  bundle: true,
  platform: "node",
  target: "node18",
  format: "esm",
  write: false,
});

if (!emitterResult.outputFiles || emitterResult.outputFiles.length === 0) {
  throw new Error("esbuild emitter pass produced no outputFiles");
}
const emitterText = emitterResult.outputFiles[0].text;
const emitterGeneratedPath = "src/pi-driver/emitter-bundle.generated.ts";
const emitterHeader = "// AUTO-GENERATED by build.mjs — do not edit by hand.\n";
const emitterFileBody =
  emitterHeader +
  `export const PI_EMITTER_SOURCE: string = ${JSON.stringify(emitterText)};\n`;
mkdirSync(dirname(emitterGeneratedPath), { recursive: true });
writeFileSync(emitterGeneratedPath, emitterFileBody, "utf8");

// ── Pass 2: bundle the server (same call shape as before) ───────────

await esbuild.build({
  entryPoints: ["src/gravity-server.ts"],
  bundle: true,
  platform: "node",
  target: "node18",
  format: "esm",
  outfile: "dist/gravity-server.mjs",
  external: [
    "net", "fs", "path", "child_process", "os", "crypto", "stream", "util", "events",
  ],
  banner: {
    js: `
import { createRequire as __createRequire } from "module";
import { fileURLToPath as __fileURLToPath } from "url";
import { dirname as __dirnameFn } from "path";
const require = __createRequire(import.meta.url);
const __filename = __fileURLToPath(import.meta.url);
const __dirname = __dirnameFn(__filename);
`,
  },
});

console.log("Built dist/gravity-server.mjs");
