import * as esbuild from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

// ── Pass 1: bundle the pi extension into an in-memory string ────────
//
// The extension is embedded as a string constant in the server build so
// `dist/gravity-server.mjs` is fully self-contained at runtime (no
// sibling artifact lookup, no `__dirname` reads for the emitter). See
// plan.md §2 "Distribution mechanism" for why this shape was chosen.

const emitterResult = await esbuild.build({
  entryPoints: ["src/pi-driver/emitter/index.ts"],
  bundle: true,
  platform: "node",
  target: "node18",
  format: "esm",
  write: false,
});

if (!emitterResult.outputFiles || emitterResult.outputFiles.length === 0) {
  throw new Error("esbuild emitter pass produced no outputFiles");
}
const emitterText = emitterResult.outputFiles[0].text;
const emitterGeneratedPath = "src/pi-driver/emitter-bundle.generated.ts";
const emitterHeader = "// AUTO-GENERATED by build.mjs — do not edit by hand.\n";
const emitterFileBody =
  emitterHeader +
  `export const PI_EMITTER_SOURCE: string = ${JSON.stringify(emitterText)};\n`;
mkdirSync(dirname(emitterGeneratedPath), { recursive: true });
writeFileSync(emitterGeneratedPath, emitterFileBody, "utf8");

// ── Pass 2: bundle the server (same call shape as before) ───────────

await esbuild.build({
  entryPoints: ["src/gravity-server.ts"],
  bundle: true,
  platform: "node",
  target: "node18",
  format: "esm",
  outfile: "dist/gravity-server.mjs",
  external: [
    "net", "fs", "path", "child_process", "os", "crypto", "stream", "util", "events",
  ],
  banner: {
    js: `
import { createRequire as __createRequire } from "module";
import { fileURLToPath as __fileURLToPath } from "url";
import { dirname as __dirnameFn } from "path";
const require = __createRequire(import.meta.url);
const __filename = __fileURLToPath(import.meta.url);
const __dirname = __dirnameFn(__filename);
`,
  },
});

console.log("Built dist/gravity-server.mjs");
